### ISSUE TITLE
Race with setting tab metadata

### ISSUE THREAD

**Issue by luphoria** [MercuryWorkshop/aboutproxy#2]
Culprit is `handleOnload`: https://github.com/MercuryWorkshop/aboutproxy/blob/a7ace34f9f48787d703746a88f2d1f365b68de3c/static/browser.js#L292

Repro:
 - go to a location in one tab
 - before tab has fully loaded, change tabs
 - tab metadata will get plastered on the new tab you just opened

**Comment by r58Playz** [comment]
yeah this should probably be tied to tabEl or the iframe

**Comment by cohenerickson** [comment]
I recommend having all processes for updating any information about a tab run as a part of a `Tab` class. That way you are only modifying `this`.
