### ISSUE TITLE
Chrome is getting a major refresh

### ISSUE THREAD

**Issue by Nebelung-Dev** [MercuryWorkshop/aboutproxy#3]
I have chrome dev build and I just got the new Chrome refresh 2023. I would be cool to see this use the new style.
![image](https://github.com/MercuryWorkshop/aboutproxy/assets/81875430/045e946a-3df1-4401-ae6b-cc58f2062394)
![image](https://github.com/MercuryWorkshop/aboutproxy/assets/81875430/51515e2a-eba8-4a9d-adbd-d26c3f23129b)
![image](https://github.com/MercuryWorkshop/aboutproxy/assets/81875430/daf0dccc-26a1-466e-865e-476689f0dac8)

More about it: https://9to5google.com/2023/05/01/google-chrome-refresh-material-you/

**Comment by CoolElectronics** [comment]
god that looks fucking awful

**Comment by Nebelung-Dev** [comment]
No.

**Comment by r58Playz** [comment]
The UI has been refreshed (ish)
